server:
  port: 8761

eureka:
  instance:
    # Правильно: совпадает с именем сервиса в docker-compose
    hostname: eureka-server 
    # Важно: для сервера оставляем false, чтобы он не подставлял свой внутренний IP контейнера
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # ВНИМАНИЕ: Для самого сервера в defaultZone лучше использовать localhost, 
      # либо оставить поле пустым, раз register-with-eureka: false.
      defaultZone: http://localhost:8761/eureka/